## Data Cleaning and Quality Report

**Project: IndiaKart E-Commerce Analytics project Sales Data Analysis**

# Objective :
 
Assess the quality of the datasets by checking:
    1 Missing values
    2 Duplicate records
    3 Data types
    4 Referential integrity
    5 Business rules

## Load all csv file

In [1]:
import zipfile
import pandas as pd
import numpy as np

#Path to the zip file
zip_path = r"c:\Users\hp\Downloads\44120013dcc669c383d89c8c4a40b746.zip"

#Dictionary to store all csv files
dataframes = {}
with zipfile.ZipFile(zip_path, 'r') as z:
    #List all the files in the zip
    display(z.namelist())

    #Read only csv files
    for file in z.namelist():
        if file.endswith('.csv'):
            with z.open(file) as f:
                df = pd.read_csv(f)
                dataframes[file] = df
#Display the first five rows of each csv                
for name, df in dataframes.items():
    display(f"\n {name}:")
    display(df.head())

['customers DA.csv',
 'data_dictionary __ fin.md',
 'IndiaKart_Project_PRD__.docx',
 'inventory DA.csv',
 'order_items DA.csv',
 'orders DA.csv',
 'payments DA.csv',
 'products DA.csv',
 'returns DA.csv',
 'schema_and_sql final internmo.sql',
 'suppliers DA.csv']

'\n customers DA.csv:'

,customer_id,first_name,last_name,email,phone,city,state,pincode,gender,age,segment,registration_date,last_login_date,is_verified,is_active,total_orders,total_spent
0,CUST00001,Kunal,Gupta,kunal.gupta223@gmail.com,9117912889,Guwahati,Assam,314040,Male,54,New,30-07-2024,10-04-2025,0,1,7,1028341.51
1,CUST00002,Aryan,Gupta,aryan.gupta336@yahoo.in,9271550550,Navi Mumbai,Maharashtra,799535,Female,26,Budget,05-07-2023,03-05-2024,1,1,1,20337.39
2,CUST00003,Akash,Chatterjee,akash.chatterjee584@hotmail.com,9559676548,Surat,Gujarat,738196,Female,24,Regular,14-05-2022,31-10-2023,1,1,7,265688.26
3,CUST00004,Madhuri,Walia,madhuri.walia878@gmail.com,9673322422,Gwalior,Madhya Pradesh,238106,Female,23,Regular,21-01-2025,22-05-2025,1,0,7,173446.94
4,CUST00005,Vishal,Das,vishal.das342@yahoo.in,9920855521,Dhanbad,Jharkhand,783291,Female,59,Regular,06-06-2023,29-03-2024,1,0,4,239808.60

'\n inventory DA.csv:'

,inventory_id,product_id,warehouse_location,quantity_available,quantity_reserved,reorder_level,reorder_quantity,last_restocked_date,unit_cost,total_inventory_value,status
0,INV0001,PRD0001,Hyderabad-WH4,13,4,49,245,11-09-2023,55738,724594,Low Stock
1,INV0002,PRD0002,Kolkata-WH6,368,14,50,250,10-03-2025,48052,17683136,In Stock
2,INV0003,PRD0003,Delhi-WH2,196,19,44,220,22-11-2024,68913,13506948,In Stock
3,INV0004,PRD0004,Delhi-WH2,432,10,19,57,10-11-2024,80055,34583760,In Stock
4,INV0005,PRD0005,Bengaluru-WH3,404,16,44,88,05-08-2024,8398,3392792,In Stock

'\n order_items DA.csv:'

,item_id,order_id,product_id,product_name,category,quantity,unit_price,gst_rate,gst_amount,discount_amount,total_price
0,ITM0000001,ORD000001,PRD0522,HCL Cricket Bat Ultra,Sports & Fitness,1,40989,12,4918.68,7861.45,38046.23
1,ITM0000002,ORD000001,PRD0094,Berger Router Pro,Electronics,1,62532,18,11255.76,12373.11,61414.65
2,ITM0000003,ORD000001,PRD0613,Voltas Educational Toy Standard,Toys & Baby,1,1585,12,190.20,251.89,1523.31
3,ITM0000004,ORD000002,PRD0556,Ambrane Cycle Standard,Sports & Fitness,3,1107,12,398.52,631.44,3088.08
4,ITM0000005,ORD000002,PRD0026,Pebble Tablet Premium,Electronics,2,114448,18,41201.28,18707.35,251389.93

'\n orders DA.csv:'

,order_id,customer_id,order_date,order_time,status,city,state,pincode,total_amount,gst_amount,shipping_charge,discount_amount,final_amount,payment_method,shipping_partner,tracking_id,delivered_date,is_cod,channel
0,ORD000001,CUST02946,22-05-2025,17:10:00,Processing,Pune,Maharashtra,300862,100984.19,16364.64,0,20486.45,100984.19,Cash on Delivery,BlueDart,TRK354572763,NaN,1,App
1,ORD000002,CUST04232,16-10-2023,05:32:00,Delivered,Ludhiana,Punjab,387852,254478.01,41599.80,0,19338.79,254478.01,UPI,DTDC,TRK272838570,19-10-2023,0,Website
2,ORD000003,CUST08078,08-10-2023,12:32:00,Cancelled,Meerut,Uttar Pradesh,294014,32557.06,3562.92,0,696.86,32557.06,Debit Card,Amazon Logistics,TRK338505401,NaN,0,App
3,ORD000004,CUST09612,02-10-2023,08:05:00,Delivered,Nashik,Maharashtra,626047,24836.94,3092.88,0,4029.94,24836.94,UPI,DTDC,TRK289792017,09-10-2023,0,Mobile Web
4,ORD000005,CUST03065,15-06-2024,20:19:00,Delivered,Moradabad,Uttar Pradesh,409210,156689.29,25092.36,0,7805.07,156689.29,UPI,Ecom Express,TRK978240041,22-06-2024,0,App

'\n payments DA.csv:'

,payment_id,order_id,customer_id,payment_date,payment_time,payment_method,amount,status,transaction_id,bank_name,gateway,refund_amount,refund_date
0,PAY000001,ORD000001,CUST02946,22-05-2025,17:10:00,Cash on Delivery,100984.19,Success,TXN5110698474,SBI,Google Pay,0,NaN
1,PAY000002,ORD000002,CUST04232,16-10-2023,05:32:00,UPI,254478.01,Success,TXN4067460377,IndusInd,Google Pay,0,NaN
2,PAY000003,ORD000003,CUST08078,08-10-2023,12:32:00,Debit Card,32557.06,Success,TXN7056710694,Axis Bank,PhonePe,0,NaN
3,PAY000004,ORD000004,CUST09612,02-10-2023,08:05:00,UPI,24836.94,Success,TXN7460208257,Axis Bank,PhonePe,0,NaN
4,PAY000005,ORD000005,CUST03065,15-06-2024,20:19:00,UPI,156689.29,Success,TXN5835043807,PNB,Razorpay,0,NaN

'\n products DA.csv:'

,product_id,product_name,category,subcategory,brand,sku,mrp,selling_price,cost_price,gst_rate,hsn_code,weight_grams,supplier_id,rating,review_count,is_active,launch_date
0,PRD0001,Usha Smartphone Elite,Electronics,Smartphone,Usha,SKU-ELE-00001,92028,78958,55738,18,1144,250,SUP0198,4.3,3655,1,29-01-2025
1,PRD0002,Gizmore Smartphone Premium,Electronics,Smartphone,Gizmore,SKU-ELE-00002,91470,65917,48052,18,2857,2000,SUP0140,3.6,2321,1,17-05-2024
2,PRD0003,Fire-Boltt Smartphone Max,Electronics,Smartphone,Fire-Boltt,SKU-ELE-00003,148029,118800,68913,18,2349,250,SUP0113,3.5,4412,1,28-12-2024
3,PRD0004,Godrej Smartphone Elite,Electronics,Smartphone,Godrej,SKU-ELE-00004,152903,113203,80055,18,8130,250,SUP0068,4.5,1264,1,04-05-2023
4,PRD0005,HDFC Smartphone Elite,Electronics,Smartphone,HDFC,SKU-ELE-00005,18715,16226,8398,18,4729,1000,SUP0088,3.9,3700,1,27-11-2023

'\n returns DA.csv:'

,return_id,order_id,customer_id,return_date,reason,return_amount,refund_status,refund_date,return_condition,remarks
0,RET00001,ORD000015,CUST05470,23-12-2024,Size Issue,24167.33,Pending,30-12-2024,Damaged,Customer initiated return within 7 day window
1,RET00002,ORD000017,CUST07581,01-11-2023,Defective Product,11698.27,Refunded,06-11-2023,Damaged,Customer initiated return within 7 day window
2,RET00003,ORD000038,CUST05691,01-05-2025,Wrong Product Delivered,11147.74,Refunded,06-05-2025,Damaged,Customer initiated return within 7 day window
3,RET00004,ORD000054,CUST03170,20-06-2025,Duplicate Order,9284.55,Refunded,24-06-2025,Acceptable,Customer initiated return within 7 day window
4,RET00005,ORD000072,CUST09318,16-03-2025,Duplicate Order,36912.59,Refunded,23-03-2025,Good,Customer initiated return within 7 day window

'\n suppliers DA.csv:'

,supplier_id,supplier_name,contact_person,email,phone,city,state,pincode,category,gstin,payment_terms_days,rating,created_date,is_active
0,SUP0001,Iyer Elec Pvt Ltd,Harish Iyer,contact@iyerele.com,9362950628,Delhi,Delhi,334053,Electronics,14TRXCK1488C4Z9,15,4.1,22-05-2023,1
1,SUP0002,Sharma Offi Pvt Ltd,Mohit Sharma,contact@sharmaoff.com,9914763202,Ahmedabad,Gujarat,267414,Office Supplies,32KHFTC7224C6Z5,15,4.5,25-03-2023,1
2,SUP0003,Choudhury Beau Pvt Ltd,Nandini Choudhury,contact@choudhurybea.com,9764130526,Pune,Maharashtra,479201,Beauty & Health,28EBRUZ4814W7Z5,60,4.3,27-12-2022,1
3,SUP0004,Choudhury Fash Pvt Ltd,Vikram Choudhury,contact@choudhuryfas.com,9283758720,Chennai,Tamil Nadu,660086,Fashion,33GMHYR4598R1Z4,15,4.6,15-01-2023,1
4,SUP0005,Patil Spor Pvt Ltd,Kiran Patil,contact@patilspo.com,9636045484,Jaipur,Rajasthan,514850,Sports & Fitness,30LGGOG8019X7Z6,30,5.0,02-09-2022,1

# Basic Data Profiling :

In [2]:
# 2. For each table: row count, column count, data types
for name, df in dataframes.items():
    display(f"\nProfile for {name}:")
    display(f"Row count: {df.shape[0]}")
    display(f"Column count: {df.shape[1]}")
    display(f"Data types:\n{df.dtypes}")

'\nProfile for customers DA.csv:'

'Row count: 10000'

'Column count: 17'

'Data types:\ncustomer_id              str\nfirst_name               str\nlast_name                str\nemail                    str\nphone                  int64\ncity                     str\nstate                    str\npincode                int64\ngender                   str\nage                    int64\nsegment                  str\nregistration_date        str\nlast_login_date          str\nis_verified            int64\nis_active              int64\ntotal_orders           int64\ntotal_spent          float64\ndtype: object'

'\nProfile for inventory DA.csv:'

'Row count: 1000'

'Column count: 11'

'Data types:\ninventory_id               str\nproduct_id                 str\nwarehouse_location         str\nquantity_available       int64\nquantity_reserved        int64\nreorder_level            int64\nreorder_quantity         int64\nlast_restocked_date        str\nunit_cost                int64\ntotal_inventory_value    int64\nstatus                     str\ndtype: object'

'\nProfile for order_items DA.csv:'

'Row count: 100000'

'Column count: 11'

'Data types:\nitem_id                str\norder_id               str\nproduct_id             str\nproduct_name           str\ncategory               str\nquantity             int64\nunit_price           int64\ngst_rate             int64\ngst_amount         float64\ndiscount_amount    float64\ntotal_price        float64\ndtype: object'

'\nProfile for orders DA.csv:'

'Row count: 50000'

'Column count: 19'

'Data types:\norder_id                str\ncustomer_id             str\norder_date              str\norder_time              str\nstatus                  str\ncity                    str\nstate                   str\npincode               int64\ntotal_amount        float64\ngst_amount          float64\nshipping_charge       int64\ndiscount_amount     float64\nfinal_amount        float64\npayment_method          str\nshipping_partner        str\ntracking_id             str\ndelivered_date          str\nis_cod                int64\nchannel                 str\ndtype: object'

'\nProfile for payments DA.csv:'

'Row count: 50000'

'Column count: 13'

'Data types:\npayment_id            str\norder_id              str\ncustomer_id           str\npayment_date          str\npayment_time          str\npayment_method        str\namount            float64\nstatus                str\ntransaction_id        str\nbank_name             str\ngateway               str\nrefund_amount       int64\nrefund_date       float64\ndtype: object'

'\nProfile for products DA.csv:'

'Row count: 1000'

'Column count: 17'

'Data types:\nproduct_id           str\nproduct_name         str\ncategory             str\nsubcategory          str\nbrand                str\nsku                  str\nmrp                int64\nselling_price      int64\ncost_price         int64\ngst_rate           int64\nhsn_code           int64\nweight_grams       int64\nsupplier_id          str\nrating           float64\nreview_count       int64\nis_active          int64\nlaunch_date          str\ndtype: object'

'\nProfile for returns DA.csv:'

'Row count: 10000'

'Column count: 10'

'Data types:\nreturn_id               str\norder_id                str\ncustomer_id             str\nreturn_date             str\nreason                  str\nreturn_amount       float64\nrefund_status           str\nrefund_date             str\nreturn_condition        str\nremarks                 str\ndtype: object'

'\nProfile for suppliers DA.csv:'

'Row count: 200'

'Column count: 14'

'Data types:\nsupplier_id               str\nsupplier_name             str\ncontact_person            str\nemail                     str\nphone                   int64\ncity                      str\nstate                     str\npincode                 int64\ncategory                  str\ngstin                     str\npayment_terms_days      int64\nrating                float64\ncreated_date              str\nis_active               int64\ndtype: object'

# Missing value Analysis

In [3]:
## 3. Missing values in every column —columns have nulls and % of rows affected.
print("="*70)
print("MISSING VALUE ANALYSIS")
print("="*70)

for name, df in dataframes.items():

    print(f"\n{name}")

    missing = df.isna().sum()

    missing = missing[missing > 0]

    if missing.empty:
        print("No missing values.")
        continue

    result = pd.DataFrame({
        "Missing Values": missing,
        "% Rows Affected": (missing / len(df) * 100).round(2)
    })

    print(result)

======================================================================
MISSING VALUE ANALYSIS
======================================================================

customers DA.csv
No missing values.

inventory DA.csv
No missing values.

order_items DA.csv
No missing values.

orders DA.csv
                Missing Values  % Rows Affected
delivered_date           17501             35.0

payments DA.csv
             Missing Values  % Rows Affected
refund_date           50000            100.0

products DA.csv
No missing values.

returns DA.csv
No missing values.

suppliers DA.csv
No missing values.

# Duplicate Record Analysis

In [4]:
# 4. For each table, check for duplicate rows and report the count of duplicates.
for name, df in dataframes.items():
    display(f"\nDuplicate rows for {name}:")
    duplicate_rows = df.duplicated().sum()
    display(f"Number of duplicate rows: {duplicate_rows}")

# Duplicate order_id in orders.csv
if 'orders.csv' in dataframes:
    orders_df = dataframes['orders.csv']
    duplicate_order_ids = orders_df[orders_df.duplicated(subset='order_id', keep=False)]
    display(f"\nDuplicate order_id in orders.csv:")
    display(duplicate_order_ids)

'\nDuplicate rows for customers DA.csv:'

'Number of duplicate rows: 0'

'\nDuplicate rows for inventory DA.csv:'

'Number of duplicate rows: 0'

'\nDuplicate rows for order_items DA.csv:'

'Number of duplicate rows: 0'

'\nDuplicate rows for orders DA.csv:'

'Number of duplicate rows: 0'

'\nDuplicate rows for payments DA.csv:'

'Number of duplicate rows: 0'

'\nDuplicate rows for products DA.csv:'

'Number of duplicate rows: 0'

'\nDuplicate rows for returns DA.csv:'

'Number of duplicate rows: 0'

'\nDuplicate rows for suppliers DA.csv:'

'Number of duplicate rows: 0'

# Data type Validation

In [5]:
# 5. Validate the data types of each column in every table and convert date columns to datetime format. 
for name, df in dataframes.items():
    display(f"\nData types for {name}:")
    display(df.dtypes)

    # Convert date columns to datetime format
    for column in df.columns:
        if 'date' in column.lower():
            try:
                df[column] = pd.to_datetime(df[column], errors='coerce')
                display(f"Converted column '{column}' to datetime format.")
            except Exception as e:
                display(f"Could not convert column '{column}' to datetime format: {e}")
    display("\nUpdated data types after conversion:")
    display(df.dtypes)

'\nData types for customers DA.csv:'

customer_id              str
first_name               str
last_name                str
email                    str
phone                  int64
city                     str
state                    str
pincode                int64
gender                   str
age                    int64
segment                  str
registration_date        str
last_login_date          str
is_verified            int64
is_active              int64
total_orders           int64
total_spent          float64
dtype: object

C:\Users\hp\AppData\Local\Temp\ipykernel_11736\4048023095.py:10: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[column] = pd.to_datetime(df[column], errors='coerce')

"Converted column 'registration_date' to datetime format."

"Converted column 'last_login_date' to datetime format."

'\nUpdated data types after conversion:'

customer_id                     str
first_name                      str
last_name                       str
email                           str
phone                         int64
city                            str
state                           str
pincode                       int64
gender                          str
age                           int64
segment                         str
registration_date    datetime64[us]
last_login_date      datetime64[us]
is_verified                   int64
is_active                     int64
total_orders                  int64
total_spent                 float64
dtype: object

'\nData types for inventory DA.csv:'

inventory_id               str
product_id                 str
warehouse_location         str
quantity_available       int64
quantity_reserved        int64
reorder_level            int64
reorder_quantity         int64
last_restocked_date        str
unit_cost                int64
total_inventory_value    int64
status                     str
dtype: object

"Converted column 'last_restocked_date' to datetime format."

'\nUpdated data types after conversion:'

inventory_id                        str
product_id                          str
warehouse_location                  str
quantity_available                int64
quantity_reserved                 int64
reorder_level                     int64
reorder_quantity                  int64
last_restocked_date      datetime64[us]
unit_cost                         int64
total_inventory_value             int64
status                              str
dtype: object

'\nData types for order_items DA.csv:'

item_id                str
order_id               str
product_id             str
product_name           str
category               str
quantity             int64
unit_price           int64
gst_rate             int64
gst_amount         float64
discount_amount    float64
total_price        float64
dtype: object

'\nUpdated data types after conversion:'

item_id                str
order_id               str
product_id             str
product_name           str
category               str
quantity             int64
unit_price           int64
gst_rate             int64
gst_amount         float64
discount_amount    float64
total_price        float64
dtype: object

'\nData types for orders DA.csv:'

order_id                str
customer_id             str
order_date              str
order_time              str
status                  str
city                    str
state                   str
pincode               int64
total_amount        float64
gst_amount          float64
shipping_charge       int64
discount_amount     float64
final_amount        float64
payment_method          str
shipping_partner        str
tracking_id             str
delivered_date          str
is_cod                int64
channel                 str
dtype: object

C:\Users\hp\AppData\Local\Temp\ipykernel_11736\4048023095.py:10: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[column] = pd.to_datetime(df[column], errors='coerce')

"Converted column 'order_date' to datetime format."

C:\Users\hp\AppData\Local\Temp\ipykernel_11736\4048023095.py:10: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[column] = pd.to_datetime(df[column], errors='coerce')

"Converted column 'delivered_date' to datetime format."

'\nUpdated data types after conversion:'

order_id                       str
customer_id                    str
order_date          datetime64[us]
order_time                     str
status                         str
city                           str
state                          str
pincode                      int64
total_amount               float64
gst_amount                 float64
shipping_charge              int64
discount_amount            float64
final_amount               float64
payment_method                 str
shipping_partner               str
tracking_id                    str
delivered_date      datetime64[us]
is_cod                       int64
channel                        str
dtype: object

'\nData types for payments DA.csv:'

payment_id            str
order_id              str
customer_id           str
payment_date          str
payment_time          str
payment_method        str
amount            float64
status                str
transaction_id        str
bank_name             str
gateway               str
refund_amount       int64
refund_date       float64
dtype: object

C:\Users\hp\AppData\Local\Temp\ipykernel_11736\4048023095.py:10: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[column] = pd.to_datetime(df[column], errors='coerce')

"Converted column 'payment_date' to datetime format."

"Converted column 'refund_date' to datetime format."

'\nUpdated data types after conversion:'

payment_id                   str
order_id                     str
customer_id                  str
payment_date      datetime64[us]
payment_time                 str
payment_method               str
amount                   float64
status                       str
transaction_id               str
bank_name                    str
gateway                      str
refund_amount              int64
refund_date        datetime64[s]
dtype: object

'\nData types for products DA.csv:'

product_id           str
product_name         str
category             str
subcategory          str
brand                str
sku                  str
mrp                int64
selling_price      int64
cost_price         int64
gst_rate           int64
hsn_code           int64
weight_grams       int64
supplier_id          str
rating           float64
review_count       int64
is_active          int64
launch_date          str
dtype: object

C:\Users\hp\AppData\Local\Temp\ipykernel_11736\4048023095.py:10: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[column] = pd.to_datetime(df[column], errors='coerce')

"Converted column 'launch_date' to datetime format."

'\nUpdated data types after conversion:'

product_id                  str
product_name                str
category                    str
subcategory                 str
brand                       str
sku                         str
mrp                       int64
selling_price             int64
cost_price                int64
gst_rate                  int64
hsn_code                  int64
weight_grams              int64
supplier_id                 str
rating                  float64
review_count              int64
is_active                 int64
launch_date      datetime64[us]
dtype: object

'\nData types for returns DA.csv:'

return_id               str
order_id                str
customer_id             str
return_date             str
reason                  str
return_amount       float64
refund_status           str
refund_date             str
return_condition        str
remarks                 str
dtype: object

C:\Users\hp\AppData\Local\Temp\ipykernel_11736\4048023095.py:10: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[column] = pd.to_datetime(df[column], errors='coerce')

"Converted column 'return_date' to datetime format."

C:\Users\hp\AppData\Local\Temp\ipykernel_11736\4048023095.py:10: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[column] = pd.to_datetime(df[column], errors='coerce')

"Converted column 'refund_date' to datetime format."

'\nUpdated data types after conversion:'

return_id                      str
order_id                       str
customer_id                    str
return_date         datetime64[us]
reason                         str
return_amount              float64
refund_status                  str
refund_date         datetime64[us]
return_condition               str
remarks                        str
dtype: object

'\nData types for suppliers DA.csv:'

supplier_id               str
supplier_name             str
contact_person            str
email                     str
phone                   int64
city                      str
state                     str
pincode                 int64
category                  str
gstin                     str
payment_terms_days      int64
rating                float64
created_date              str
is_active               int64
dtype: object

C:\Users\hp\AppData\Local\Temp\ipykernel_11736\4048023095.py:10: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[column] = pd.to_datetime(df[column], errors='coerce')

"Converted column 'created_date' to datetime format."

'\nUpdated data types after conversion:'

supplier_id                      str
supplier_name                    str
contact_person                   str
email                            str
phone                          int64
city                             str
state                            str
pincode                        int64
category                         str
gstin                            str
payment_terms_days             int64
rating                       float64
created_date          datetime64[us]
is_active                      int64
dtype: object

# High Value Order Check

In [6]:
# 6. Are there any orders above ₹5 lakh? Flag them
for name, df in dataframes.items():
    if 'final_amount' in df.columns:
        outliers = df[df['final_amount'] > 500000]
        if not outliers.empty:
            display(f"\nOutliers in {name} (final_amount > ₹5 lakh):")
            display(outliers)
        else:
            display(f"\nNo outliers found in {name} for final_amount > ₹5 lakh.")

'\nOutliers in orders DA.csv (final_amount > ₹5 lakh):'

,order_id,customer_id,order_date,order_time,status,city,state,pincode,total_amount,gst_amount,shipping_charge,discount_amount,final_amount,payment_method,shipping_partner,tracking_id,delivered_date,is_cod,channel
33,ORD000034,CUST01867,2024-03-10,07:18:00,Delivered,Gwalior,Madhya Pradesh,714121,527178.05,87982.56,0,85216.51,527178.05,Credit Card,XpressBees,TRK426129266,2024-03-17,0,App
34,ORD000035,CUST01370,2025-05-26,17:56:00,Cancelled,Mumbai,Maharashtra,135015,532061.13,82016.52,0,11940.39,532061.13,UPI,DTDC,TRK731489123,NaT,0,App
306,ORD000307,CUST03874,2024-03-20,11:55:00,Cancelled,Raipur,Chhattisgarh,721504,550716.17,85706.88,0,40438.71,550716.17,Cash on Delivery,Delhivery,TRK499571364,NaT,1,App
583,ORD000584,CUST07624,2024-10-30,02:55:00,Delivered,Hyderabad,Telangana,487237,745667.68,126685.30,0,81057.62,745667.68,Cash on Delivery,BlueDart,TRK820123719,2024-11-04,1,Website
590,ORD000591,CUST05298,2025-05-22,04:28:00,Cancelled,Faridabad,Haryana,262336,520293.72,84126.96,0,31732.24,520293.72,Credit Card,Shadowfax,TRK957301189,NaT,0,App
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39194,ORD039195,CUST02704,2024-09-02,10:53:00,Delivered,Guwahati,Assam,730933,588456.74,95751.18,0,41919.44,588456.74,Cash on Delivery,Amazon Logistics,TRK796217398,2024-09-04,1,Website
39582,ORD039583,CUST06723,2023-06-28,07:15:00,Delivered,Meerut,Uttar Pradesh,189610,519500.64,77975.21,0,6794.57,519500.64,Debit Card,DTDC,TRK800886823,2023-07-04,0,App
39793,ORD039794,CUST04753,2024-02-02,08:01:00,Delivered,Chandigarh,Chandigarh,560393,640296.82,107943.68,0,63337.86,640296.82,Credit Card,Ecom Express,TRK701697094,2024-02-06,0,App
39804,ORD039805,CUST04071,2023-07-11,23:03:00,Delivered,Guwahati,Assam,714125,796481.05,120415.28,0,13403.23,796481.05,Net Banking,Ecom Express,TRK327250998,2023-07-15,0,App
39888,ORD039889,CUST03676,2025-04-23,05:27:00,Cancelled,Vadodara,Gujarat,741981,537504.43,89144.10,0,46884.67,537504.43,Wallet,DTDC,TRK600715906,NaT,0,Website

# Refrential Integrity Check

In [7]:
# 7. Verify referential integrity — do all order_ids in order_items.csv exist in orders.csv?
if 'order_items DA.csv' in dataframes and 'orders DA.csv' in dataframes:
    order_items_df = dataframes['order_items DA.csv']
    orders_df = dataframes['orders DA.csv']
    missing_order_ids = order_items_df[~order_items_df['order_id'].isin(orders_df['order_id'])]  
    if not missing_order_ids.empty:
        display(f"\nOrder IDs in order_items DA.csv that do not exist in orders DA.csv:")
        display(missing_order_ids)
    else:
        display("\nAll order_ids in order_items DA.csv exist in orders DA.csv.")

'\nAll order_ids in order_items DA.csv exist in orders DA.csv.'

## Data Cleaning and Quality Report

**Project: IndiaKart E-Commerce Analytics project Sales Data Analysis**

# Objective :
 
 The objective of this data quality assessment was to evaluate the completeness, 
 accuracy, consistency, and integrity of the dataset before performing any business analysis. 
 The assessment was conducted on all eight CSV files using Python (Pandas).

# Data Profiling :

All eight datasets were loaded successfully. The row count, column count and data types were reviewed.
df.shape() was used to find rows and column count. Data types of every column for each data sets were 
examined to understand the overall structure of the data sets. The data types uses along whole data sets are:
    1 str
    2 int64
    3 float64

# Missing Values :

A missing value analysis was performed on every datasets. Columns containing null values were identified.
There were only 2 dataset having column with null values. 
    1. In the Orders dataset "delivered_date" has null values with 35% rows effect. 
    2. In the Payments dataset "refund_date" has null values with 100% rows effect.
These missing values were documented for further cleaning.

# Duplicate Records :

Duplicate row was checked across all datasets. Special attention was given to the Orders table. 
There was no duplicate values found across all datasets. order_id column contains all unique ids.

# Data Type Validation :

The data types of all columns were checked to ensure consistency. Columns containing dates were
validated as date format as they were in str(object) format, while integer fields such as
quantity, pin code were confirmed.

# Outlier Detection :

Outlier analysis was performed on the final_amount column to identify transaction greater than 5 lakh.
Orders with values greater than 5 lakh were flagged as potential outlier for further business validation.
There were 312 rows flagged .

# Referential Integrity :

Relationship between tables were validated. All order_id values in the Order Items table were checked
against the Orders table to verify that every order items belonged to a valid order. There were null
unmatched items, all order_id exist in Orders table.

# Conclusion :

The data cleaning and quality assessment provided a comprehensive understanding of the dataset's 
condition before analysis. The identified issues, including missing values, duplicates rows, wrong 
data type, potential outlier and Referential integrity checks, were documented to ensure that the data sets is reliable for further analysis and dashboard development.

## Specific Checks to Run

In [8]:
# 1. orders.csv: Check if delivered_date is always after order_date. Flag rows where it is not.
if 'orders DA.csv' in dataframes:
    df = dataframes['orders DA.csv']

    #Display actual data type 
    display(df['order_date'].dtype)
    display(df['delivered_date'].dtype)

    #change datatype to date format
    for column in df.columns:
        if 'date' in column.lower():
            df[column] = pd.to_datetime(df[column], format='%d-%m-%y', errors='coerce')
    display(df['order_date'].dtype)
    display(df['delivered_date'].dtype)

    if 'delivered_date' in df.columns:
        outliers = df[df['delivered_date'] < df['order_date']]
        if not outliers.empty:
            display("\nOutliers found in dataset:")
            display(outliers)
        else:
            display("\nNo outliers found. All delivered dates are after order dates.")


# 2. Payments.csv: Count Failed vs. Success transactions. What is the failure rate?
if 'payments DA.csv' in dataframes:
    df = dataframes['payments DA.csv']
    transaction_status = df['status'].value_counts()
    total_rows = df.shape[0]
    display(transaction_status)
    for column, count in transaction_status.items():
        if count > 0:
            percentage = (count / total_rows) * 100
            display(f"{column} rate:, {percentage:.2f}%")


 # 3. Returns.csv: Does every return have a matching order_id in orders.csv?
if 'returns DA.csv' in dataframes and 'orders DA.csv' in dataframes:
    returns_df = dataframes['returns DA.csv']
    orders_df = dataframes['orders DA.csv']
    same_order_id = returns_df[~returns_df['order_id'].isin(orders_df['order_id'])]
    if not same_order_id.empty:
        display(f"\norder_id that does not match: ")
        display(same_order_id)
    else:
        display("\nEvery return have a matching order_id.")


# 4. Inventory.csv: How many products are in 'Out of Stock' status?
if 'inventory DA.csv' in dataframes:
    df = dataframes['inventory DA.csv']
    display(df['status'].value_counts())


# 5. Customers.csv: Are there customers with total_orders = 0? 
if 'customers DA.csv' in dataframes:
    df = dataframes['customers DA.csv']
    if (df['total_orders'] == 0).any():
        display("yes, there are customers with 0 orders.")
    else:
        display("There is no one with 0 orders")

dtype('<M8[us]')

dtype('<M8[us]')

dtype('<M8[us]')

dtype('<M8[us]')

'\nNo outliers found. All delivered dates are after order dates.'

status
Success    48252
Failed      1748
Name: count, dtype: int64

'Success rate:, 96.50%'

'Failed rate:, 3.50%'

'\nEvery return have a matching order_id.'

status
In Stock        922
Low Stock        76
Out of Stock      2
Name: count, dtype: int64

'yes, there are customers with 0 orders.'

# Save Cleaned Datasets

In [10]:
import os

# Create a folder to store cleaned files
output_folder = "Cleaned_Data"
os.makedirs(output_folder, exist_ok=True)

# Save every cleaned dataframe
for file_name, df in dataframes.items():

    # Remove " DA" and ".csv" from the original filename
    clean_name = file_name.replace(" DA.csv", "").replace(".csv", "")

    # Save with new name
    output_path = os.path.join(output_folder, f"cleaned_{clean_name}.csv")

    df.to_csv(output_path, index=False)

    display(f"Saved: {output_path}")

display("\nAll cleaned CSV files have been saved successfully.")

'Saved: Cleaned_Data\\cleaned_customers.csv'

'Saved: Cleaned_Data\\cleaned_inventory.csv'

'Saved: Cleaned_Data\\cleaned_order_items.csv'

'Saved: Cleaned_Data\\cleaned_orders.csv'

'Saved: Cleaned_Data\\cleaned_payments.csv'

'Saved: Cleaned_Data\\cleaned_products.csv'

'Saved: Cleaned_Data\\cleaned_returns.csv'

'Saved: Cleaned_Data\\cleaned_suppliers.csv'

'\nAll cleaned CSV files have been saved successfully.'